### ISSUE TITLE
Research JAVA Testing Solutions

### ISSUE THREAD

**Issue by ronniesong0809** [psu-agile-group/FTP-Client#59]
As developers, we are responsible for unit tests.
Take a look at [Junit4](https://junit.org/junit4/), [Junit5](https://junit.org/junit5/), [Mockito](https://site.mockito.org/), [PowerMock](https://powermock.github.io/), and [jMock](http://jmock.org/) documentation, walk-through tutorial, and other possibly solutions.

- [x] [Junit4](https://junit.org/junit4/)
- [x] [Junit5](https://junit.org/junit5/) `popular`
- [x] [Mockito](https://site.mockito.org/) `popular`
- [x] [PowerMock](https://powermock.github.io/)
- [x] [jMock](http://jmock.org/)

**Comment by ohyonghao** [comment]
I should be able to look at this after my Algorithm's midterm on Monday.

**Comment by Sanlinlin** [comment]
I find some unit test solutions:
[TestNG](https://testng.org/doc/)
[JUnit Test tutorial](https://www.tutorialspoint.com/junit/junit_test_framework)
[Mockito tutorial](https://www.vogella.com/tutorials/Mockito/article.html)
Hope these solutions can help us :)

**Comment by ddveloper** [comment]
- One JUnit test for "put" command is committed in my "unit_test_putCommand" branch, which you can refer to.
- It's not ideal solution now (initialization part is in class constructor function, which could be put in a shared base-class properly, I didn't make the base-class way working, so see if you can improve it).
- the auto test is failing because no local "UnitTest" folder exists, the "UnitTest" folder is required in working directory to pass the "put" test, the folder can be found on the ftp server under htdocs (need to figure out how to add the folder into the auto build engine)
